### ISSUE TITLE
I would like to inquire about an issue with the code - (Python Interpreter)

### ISSUE THREAD

**Issue by amanohatosan** [KosumovicDenis/RSoftCAD.py#1]
Hello, I encountered an error in "Cad.py" when attempting to run "main.py," as depicted in the attached image. Additionally, I was unable to locate "RSoftCircuit.py" within the "rstools" package.
![5S N0D1L_(XT3PIL2(PDSUW](https://github.com/KosumovicDenis/RSoftCAD.py/assets/120023478/6fda59d8-feb2-40a1-8f5f-dd30fa43ab29)
![DALBAGJHG~7B~H6@4{KX~6E](https://github.com/KosumovicDenis/RSoftCAD.py/assets/120023478/cb6f1e63-dd2e-4ef0-b577-b6b725b86c53)

**Comment by KosumovicDenis** [comment]
Hello,

Thank you for reaching out. It seems there might be an issue with the Python interpreter. In addition to checking that you are using the correct interpreter path, please make sure to follow the instructions provided in the [repository documentation](https://github.com/KosumovicDenis/RSoftCAD.py#how-to-run-the-code).

Ensure that you are using the correct Python interpreter path, which should be something like:
```
C:/Synopsys/PhotonicSolutions/2019.09/RSoft/bin/rspython.exe
```

If the issue persists, please provide more details or share any error messages you receive so that we can offer further assistance.

Best regards.

**Comment by KosumovicDenis** [comment]
Hello,

Thank you for reaching out. It seems there might be an issue with the Python interpreter. In addition to checking that you are using the correct interpreter path, please make sure to follow the instructions provided in the [repository documentation](https://github.com/KosumovicDenis/RSoftCAD.py#how-to-run-the-code).

Ensure that you are using the correct Python interpreter path, which should be something like:
```
C:/Synopsys/PhotonicSolutions/2019.09/RSoft/bin/rspython.exe
```

If the issue persists, please provide more details or share any error messages you receive so that we can offer further assistance.

Best regards.

**Comment by amanohatosan** [comment]
I'm sorry to bother you. I would like to ask whether the author uses PyCharm or VS Code as the platform.

**Comment by amanohatosan** [comment]
When I choose "rspython.exe" as the interpreter, a filename error occurs, but if I change the filename to "python.exe," it can be used as the interpreter.

**Comment by amanohatosan** [comment]
Thank you for helping me with the answers!
![LCG25NSK~UHK@73K0)B)ZPS](https://github.com/KosumovicDenis/RSoftCAD.py/assets/120023478/d32f721e-bb65-4da4-9078-f1519cfdac9b)

**Comment by KosumovicDenis** [comment]
> I'm sorry to bother you. I would like to ask whether the author uses PyCharm or VS Code as the platform.

No bother at all, we use Visual Studio Code. If you have any more questions or need further information, feel free to ask!

**Comment by KosumovicDenis** [comment]
> Thank you for helping me with the answers!

Happy to help!

**Comment by amanohatosan** [comment]
Thank you for your response. It seems to be an issue caused by "PyCharm." "PyCharm" has specific requirements for the interpreter's directory, and the non-empty directory of RSoft-CAD triggers an error. I attempted to switch to "VS code," and now the issue has been resolved, allowing the code to run successfully.

**Comment by amanohatosan** [comment]
By the way, I would like to inquire about how to change the "Simulation" module to another module, for example, "DiffractMOD."

**Comment by KosumovicDenis** [comment]
> By the way, I would like to inquire about how to change the "Simulation" module to another module, for example, "DiffractMOD."

For the specific request to change the "Simulation" module to "DiffractMOD," this seems to be a significant change that might warrant a separate issue to ensure clarity and focused discussion. I opened one [here](https://github.com/KosumovicDenis/RSoftCAD.py/issues/2).
